const PRODUCTS = {
  impression: [
    { nom: "Produit 1", prix: "0 FCFA" },
    { nom: "Produit 2", prix: "0 FCFA" },
    { nom: "Produit 3", prix: "0 FCFA" },
    { nom: "Produit 4", prix: "0 FCFA" },
    { nom: "Produit 5", prix: "0 FCFA" },
    { nom: "Produit 6", prix: "0 FCFA" },
    { nom: "Produit 7", prix: "0 FCFA" },
    { nom: "Produit 8", prix: "0 FCFA" },
    { nom: "Produit 9", prix: "0 FCFA" },
    { nom: "Produit 10", prix: "0 FCFA" },
    { nom: "Produit 11", prix: "0 FCFA" },
    { nom: "Produit 12", prix: "0 FCFA" },
    { nom: "Produit 13", prix: "0 FCFA" },
    { nom: "Produit 14", prix: "0 FCFA" },
    { nom: "Produit 15", prix: "0 FCFA" },
    { nom: "Produit 16", prix: "0 FCFA" },
    { nom: "Produit 17", prix: "0 FCFA" },
    { nom: "Produit 18", prix: "0 FCFA" },
    { nom: "Produit 19", prix: "0 FCFA" },
    { nom: "Produit 20", prix: "0 FCFA" }
  ],

  gadgeterie: [
    { nom: "Produit 1", prix: "0 FCFA" },
    { nom: "Produit 2", prix: "0 FCFA" },
    { nom: "Produit 3", prix: "0 FCFA" },
    { nom: "Produit 4", prix: "0 FCFA" },
    { nom: "Produit 5", prix: "0 FCFA" },
    { nom: "Produit 6", prix: "0 FCFA" },
    { nom: "Produit 7", prix: "0 FCFA" },
    { nom: "Produit 8", prix: "0 FCFA" },
    { nom: "Produit 9", prix: "0 FCFA" },
    { nom: "Produit 10", prix: "0 FCFA" },
    { nom: "Produit 11", prix: "0 FCFA" },
    { nom: "Produit 12", prix: "0 FCFA" },
    { nom: "Produit 13", prix: "0 FCFA" },
    { nom: "Produit 14", prix: "0 FCFA" },
    { nom: "Produit 15", prix: "0 FCFA" },
    { nom: "Produit 16", prix: "0 FCFA" },
    { nom: "Produit 17", prix: "0 FCFA" },
    { nom: "Produit 18", prix: "0 FCFA" },
    { nom: "Produit 19", prix: "0 FCFA" },
    { nom: "Produit 20", prix: "0 FCFA" }
  ],

  invitations: [
    { nom: "Produit 1", prix: "0 FCFA" },
    { nom: "Produit 2", prix: "0 FCFA" },
    { nom: "Produit 3", prix: "0 FCFA" },
    { nom: "Produit 4", prix: "0 FCFA" },
    { nom: "Produit 5", prix: "0 FCFA" },
    { nom: "Produit 6", prix: "0 FCFA" },
    { nom: "Produit 7", prix: "0 FCFA" },
    { nom: "Produit 8", prix: "0 FCFA" },
    { nom: "Produit 9", prix: "0 FCFA" },
    { nom: "Produit 10", prix: "0 FCFA" },
    { nom: "Produit 11", prix: "0 FCFA" },
    { nom: "Produit 12", prix: "0 FCFA" },
    { nom: "Produit 13", prix: "0 FCFA" },
    { nom: "Produit 14", prix: "0 FCFA" },
    { nom: "Produit 15", prix: "0 FCFA" },
    { nom: "Produit 16", prix: "0 FCFA" },
    { nom: "Produit 17", prix: "0 FCFA" },
    { nom: "Produit 18", prix: "0 FCFA" },
    { nom: "Produit 19", prix: "0 FCFA" },
    { nom: "Produit 20", prix: "0 FCFA" }
  ],

  goodies: [
    { nom: "Produit 1", prix: "0 FCFA" },
    { nom: "Produit 2", prix: "0 FCFA" },
    { nom: "Produit 3", prix: "0 FCFA" },
    { nom: "Produit 4", prix: "0 FCFA" },
    { nom: "Produit 5", prix: "0 FCFA" },
    { nom: "Produit 6", prix: "0 FCFA" },
    { nom: "Produit 7", prix: "0 FCFA" },
    { nom: "Produit 8", prix: "0 FCFA" },
    { nom: "Produit 9", prix: "0 FCFA" },
    { nom: "Produit 10", prix: "0 FCFA" },
    { nom: "Produit 11", prix: "0 FCFA" },
    { nom: "Produit 12", prix: "0 FCFA" },
    { nom: "Produit 13", prix: "0 FCFA" },
    { nom: "Produit 14", prix: "0 FCFA" },
    { nom: "Produit 15", prix: "0 FCFA" },
    { nom: "Produit 16", prix: "0 FCFA" },
    { nom: "Produit 17", prix: "0 FCFA" },
    { nom: "Produit 18", prix: "0 FCFA" },
    { nom: "Produit 19", prix: "0 FCFA" },
    { nom: "Produit 20", prix: "0 FCFA" }
  ],

  "laser-cnc": [
    { nom: "Produit 1", prix: "0 FCFA" },
    { nom: "Produit 2", prix: "0 FCFA" },
    { nom: "Produit 3", prix: "0 FCFA" },
    { nom: "Produit 4", prix: "0 FCFA" },
    { nom: "Produit 5", prix: "0 FCFA" },
    { nom: "Produit 6", prix: "0 FCFA" },
    { nom: "Produit 7", prix: "0 FCFA" },
    { nom: "Produit 8", prix: "0 FCFA" },
    { nom: "Produit 9", prix: "0 FCFA" },
    { nom: "Produit 10", prix: "0 FCFA" },
    { nom: "Produit 11", prix: "0 FCFA" },
    { nom: "Produit 12", prix: "0 FCFA" },
    { nom: "Produit 13", prix: "0 FCFA" },
    { nom: "Produit 14", prix: "0 FCFA" },
    { nom: "Produit 15", prix: "0 FCFA" },
    { nom: "Produit 16", prix: "0 FCFA" },
    { nom: "Produit 17", prix: "0 FCFA" },
    { nom: "Produit 18", prix: "0 FCFA" },
    { nom: "Produit 19", prix: "0 FCFA" },
    { nom: "Produit 20", prix: "0 FCFA" }
  ],

  serigraphie: [
    { nom: "Produit 1", prix: "0 FCFA" },
    { nom: "Produit 2", prix: "0 FCFA" },
    { nom: "Produit 3", prix: "0 FCFA" },
    { nom: "Produit 4", prix: "0 FCFA" },
    { nom: "Produit 5", prix: "0 FCFA" },
    { nom: "Produit 6", prix: "0 FCFA" },
    { nom: "Produit 7", prix: "0 FCFA" },
    { nom: "Produit 8", prix: "0 FCFA" },
    { nom: "Produit 9", prix: "0 FCFA" },
    { nom: "Produit 10", prix: "0 FCFA" },
    { nom: "Produit 11", prix: "0 FCFA" },
    { nom: "Produit 12", prix: "0 FCFA" },
    { nom: "Produit 13", prix: "0 FCFA" },
    { nom: "Produit 14", prix: "0 FCFA" },
    { nom: "Produit 15", prix: "0 FCFA" },
    { nom: "Produit 16", prix: "0 FCFA" },
    { nom: "Produit 17", prix: "0 FCFA" },
    { nom: "Produit 18", prix: "0 FCFA" },
    { nom: "Produit 19", prix: "0 FCFA" },
    { nom: "Produit 20", prix: "0 FCFA" }
  ],

  deco: [
    { nom: "Produit 1", prix: "0 FCFA" },
    { nom: "Produit 2", prix: "0 FCFA" },
    { nom: "Produit 3", prix: "0 FCFA" },
    { nom: "Produit 4", prix: "0 FCFA" },
    { nom: "Produit 5", prix: "0 FCFA" },
    { nom: "Produit 6", prix: "0 FCFA" },
    { nom: "Produit 7", prix: "0 FCFA" },
    { nom: "Produit 8", prix: "0 FCFA" },
    { nom: "Produit 9", prix: "0 FCFA" },
    { nom: "Produit 10", prix: "0 FCFA" },
    { nom: "Produit 11", prix: "0 FCFA" },
    { nom: "Produit 12", prix: "0 FCFA" },
    { nom: "Produit 13", prix: "0 FCFA" },
    { nom: "Produit 14", prix: "0 FCFA" },
    { nom: "Produit 15", prix: "0 FCFA" },
    { nom: "Produit 16", prix: "0 FCFA" },
    { nom: "Produit 17", prix: "0 FCFA" },
    { nom: "Produit 18", prix: "0 FCFA" },
    { nom: "Produit 19", prix: "0 FCFA" },
    { nom: "Produit 20", prix: "0 FCFA" }
  ],

  social: [
    { nom: "Produit 1", prix: "0 FCFA" },
    { nom: "Produit 2", prix: "0 FCFA" },
    { nom: "Produit 3", prix: "0 FCFA" },
    { nom: "Produit 4", prix: "0 FCFA" },
    { nom: "Produit 5", prix: "0 FCFA" }
  ]
};
