const PRODUCTS = {
  impression: [
    { nom: "Fliyers A5 couleurs", prix: "100 FCFA" },
    { nom: "Bloc factures A5 paysage autocopiant", prix: "2500 FCFA" },
    { nom: "Bloc 8 facture/A4 portrait, autocopiant ", prix: "5500 FCFA" },
    { nom: "Bloc de reçus", prix: "2000 FCFA" },
    { nom: "Bloc de bon de commande A5 portrait autocopiant", prix: "2500 FCFA" },
    { nom: "Bloc factures A5 portrait autocopiant", prix: "2500 FCFA" },
    { nom: "Bloc 8 facture/A4 paysage, autocopiant", prix: "5500 FCFA" },
    { nom: "Produit 8", prix: "0 FCFA" },
    { nom: "Bloc d'ordonnances personnalisés", prix: "1500 FCFA" },
    { nom: "dépliant A4 couleurs", prix: "250 FCFA" },
    { nom: "Carte de visite / fliyer", prix: "200 FCFA" },
    { nom: "Cachet flashé avec encre rechargeable", prix: "7500 FCFA" },
    { nom: "Bâche/m2", prix: "2500 FCFA" },
    { nom: "Piste de dance/m2", prix: "2000 FCFA" },
    { nom: "Vinyl mate/m2", prix: "9000 FCFA" },
    { nom: "Vynil couleur/m2", prix: "5000 FCFA" },
    { nom: "Produit 17", prix: "0 FCFA" },
    { nom: "Album personnalisé", prix: "5000 FCFA" },
    { nom: "Set de table personnalisé", prix: "500 FCFA" },
    { nom: "Faire part des obsèques", prix: "750 FCFA" }
  ],

  gadgeterie: [
    { nom: "Boîte à dragées personnalisée", prix: "150 FCFA" },
    { nom: "Boîte à dragées personnalisée", prix: "200 FCFA" },
    { nom: "Boîte à dragées personnalisée", prix: "200 FCFA" },
    { nom: "Porte-clés personnalisé avec anneau doré", prix: "500 FCFA" },
    { nom: "Porte-clés personnalisé avec simple anneau", prix: "400 FCFA" },
    { nom: "Porte-clés personnalisé avec anneau doré", prix: "500 FCFA" },
    { nom: "Stylo personnalisé avec étui", prix: "500 FCFA" },
    { nom: "Mini ventilateur personnalisé", prix: "1500 FCFA" },
    { nom: "Shopping bag en carton A5 personnalisé", prix: "500 FCFA" },
    { nom: "Parapluie personnalisé", prix: "5000 FCFA" },
    { nom: "Clé USB en bois avec étui personnalisé ", prix: "10000 FCFA" },
    { nom: "Shopping bag en tissu A3 personnalisé", prix: "500 FCFA" },
    { nom: "Porte(clés 3D personnalisé avec anneau doré", prix: "2000 FCFA" },
    { nom: "Porte-anneaux de mariage en acrylique or/miroir", prix: "10000 FCFA" },
    { nom: "Porte-anneaux de mariage en acrylique blanc", prix: "7500 FCFA" },
    { nom: "Housses de coussins de salon personnalisés", prix: "2500 FCFA" },
    { nom: "Agenda personnalisé", prix: "4500 FCFA" },
    { nom: "Photo sur acrylique 60/40cm", prix: "12000 FCFA" },
    { nom: "Livre d'or de mariage couverture en bois personnalisé", prix: "18000 FCFA" },
    { nom: "Marque-table en acrylique", prix: "1500 FCFA" }
  ],

  invitations: [
    { nom: "Invitation transparente PVC", prix: "750 FCFA" },
    { nom: "Invitation en carton chic", prix: "600 FCFA" },
    { nom: "Invitation en bois", prix: "750 FCFA" },
    { nom: "Invitation en carton style corsais", prix: "600 FCFA" },
    { nom: "Invitation transparente PVC", prix: "750 FCFA" },
    { nom: "Invitation en carton bordure arrondie", prix: "500 FCFA" },
    { nom: "Invitation en acrylique transparent", prix: "1200 FCFA" },
    { nom: "Invitation en acrylique transparent", prix: "1200 FCFA" },
    { nom: "invitation en carton rouge et blanc", prix: "500 FCFA" },
    { nom: "invitation vert olive", prix: "650 FCFA" },
    { nom: "Invitation orange brulé", prix: "500 FCFA" },
    { nom: "Invitation croisé", prix: "500 FCFA" },
    { nom: "Invitation craft", prix: "500 FCFA" },
    { nom: "Invitation avec papillon", prix: "500 FCFA" },
    { nom: "Invitation vert éméraude", prix: "500 FCFA" },
    { nom: "Invitation vert olive croisée", prix: "500 FCFA" },
    { nom: "Invitation en bois", prix: "750 FCFA" },
    { nom: "Invitation en carton mauve", prix: "500 FCFA" },
    { nom: "Invitation mariage traditionnel", prix: "500 FCFA" },
    { nom: "Invitation acrylique or/miroir", prix: "2000 FCFA" }
  ],

  goodies: [
    { nom: "Casquette", prix: "2000 FCFA" },
    { nom: "Porte-documents", prix: "15000 FCFA" },
    { nom: "Gourde personnalisée", prix: "3000 FCFA" },
    { nom: "Parapluie personnalisé", prix: "3500 FCFA" },
    { nom: "Produit 5", prix: "0 FCFA" },
    { nom: "Clé USB 8GB personnalisé", prix: "2500 FCFA" },
    { nom: "Calendrier", prix: "750 FCFA" },
    { nom: "Echarpe peronnalisée", prix: "1500 FCFA" },
    { nom: "Carte de visite(lot de 100)", prix: "7500 FCFA" },
    { nom: "Gourde personnalisée enfant", prix: "3500 FCFA" },
    { nom: "Porte-clés personnalisés avec simple anneau", prix: "400 FCFA" },
    { nom: "Tasse personnalisée", prix: "2500 FCFA" },
    { nom: "Roll-up personnalisé", prix: "25000 FCFA" },
    { nom: "Casque peronnalisé", prix: "7500 FCFA" },
    { nom: "Polo imprimé personnalisé", prix: "4000 FCFA" },
    { nom: "Polo brodé personnalisé", prix: "5000 FCFA" },
    { nom: "Produit 17", prix: "0 FCFA" },
    { nom: "Présentoir d'ongles vernis en acrylique", prix: "5000 FCFA" },
    { nom: "Corde de badge personnalisée", prix: "750 FCFA" },
    { nom: "Agenda et gourde personnalisés", prix: "15000 FCFA" }
  ],

  "laser-cnc": [
    { nom: "Trophée de match en bois", prix: "7500 FCFA" },
    { nom: "Trophée en acrylique noir", prix: "7500 FCFA" },
    { nom: "Médaille en acrylique transparent et or", prix: "1000 FCFA" },
    { nom: "Médaille en acrylique noir et or/miroir", prix: "750 FCFA" },
    { nom: "Médaille imprimé sur acrylique transparent", prix: "600 FCFA" },
    { nom: "Trophée imprimé sur acrylique transparent", prix: "5000 FCFA" },
    { nom: "Trophée imprimé sur acrylique transparent", prix: "5000 FCFA" },
    { nom: "Trophée 3D en acrylique transparent", prix: "7500 FCFA" },
    { nom: "Produit 9", prix: "0 FCFA" },
    { nom: "Carte de visite gravée sur du bois", prix: "400 FCFA" },
    { nom: "Agenda et stylo en bois gravés", prix: "12000 FCFA" },
    { nom: "Stylo en bois avec coffret personnalisé", prix: "15000 FCFA" },
    { nom: "Tableau 3D personnalisé en bois", prix: "8500 FCFA" },
    { nom: "Invitation gravé", prix: "1000 FCFA" },
    { nom: "Porte-bouteille de vin en bois", prix: "7500 FCFA" },
    { nom: "Horloge de table en bois", prix: "10000 FCFA" },
    { nom: "Médaille en acrylique transparent et o", prix: "1000 FCFA" },
    { nom: "Marque-table en bois", prix: "1000 FCFA" },
    { nom: "Gravure sur marbre, granite/lettre", prix: "400 FCFA" },
    { nom: "Gravure sur marbre, granite/lettre + photo", prix: "400 FCFA" }
  ],

  serigraphie: [
    { nom: "Plaque lumineuse 3D/taille de lettre", prix: "2500 FCFA" },
    { nom: "Plaque lumineuse d'intérieure en acrylique transparent 50cm", prix: "50000 FCFA" },
    { nom: "Plaque lumineuse en acrylique blanc 50cm", prix: "45000 FCFA" },
    { nom: "Plaque lumineuse découpée sur alucobond 3 m2", prix: "120000 FCFA" },
    { nom: "Signalétique routière sur vynil fluorescent/m2", prix: "3000 FCFA" },
    { nom: "Habillage vynil microperforé/m2", prix: "9500 FCFA" },
    { nom: "roll-up", prix: "25000 FCFA" },
    { nom: "Pagne personnalisé", prix: "7500 FCFA" },
    { nom: "Flocage de maillot", prix: "1500 FCFA" },
    { nom: "Flocage de survêtement", prix: "2000 FCFA" },
    { nom: "Chasuble personnalisé", prix: "4000 FCFA" },
    { nom: "Impression T.shirt", prix: "2500 FCFA" },
    { nom: "Sac plastique personnalisé", prix: "150 FCFA" },
    { nom: "Plaque mobile recto/verso", prix: "35000 FCFA" },
    { nom: "Impression et découpe étiquettes autocollants", prix: "50 FCFA" },
    { nom: "Cachet personnalisé de savon", prix: "5000 FCFA" },
    { nom: "Packaging sérum personnalisé", prix: "250 FCFA" },
    { nom: "Porte-menu en acrylique", prix: "3000 FCFA" },
    { nom: "Plaque de QR réseaux sociaux ", prix: "10000 FCFA" },
    { nom: "Plaque d'orientation en bois et acrylique", prix: "25000" }
  ],

  deco: [
    { nom: "Lampe en bois", prix: "7000 FCFA" },
    { nom: "Guéridon en bois avec frises", prix: "15000 FCFA" },
    { nom: "Montre en bois avec frises", prix: "20000 FCFA" },
    { nom: "Tableau en bois 3D", prix: "60000 FCFA" },
    { nom: "séparation en bois", prix: "50000 FCFA" },
    { nom: "Plateau en bois", prix: "7000 FCFA" },
    { nom: "séparation en bois", prix: "50000 FCFA" },
    { nom: "Porte en bois", prix: "40000 FCFA" },
    { nom: "tableau de 3 pièces en alucobond", prix: "60000 FCFA" },
    { nom: "Montre murale en bois et acrylique", prix: "25000 FCFA" },
    { nom: "Tableau mural avec des frises", prix: "40000 FCFA" },
    { nom: "Horloge murale personnalisée en bois", prix: "20000 FCFA" },
    { nom: "Décoration de maison en bois", prix: "8500 FCFA" },
    { nom: " Sous-tasse en bois 6 pièces", prix: "5000 FCFA" },
    { nom: "Sous-plats en bois", prix: "10000 FCFA" },
    { nom: "Porte-bijoux en bois personnalisé", prix: "8500 FCFA" },
    { nom: "Porte-mouchoirs en bois", prix: "8500 FCFA" },
    { nom: "Porte-vins en bois pour 3 bouteilles", prix: "10000 FCFA" },
    { nom: "Meuble de décoration murale", prix: "10000 FCFA" },
    { nom: "Photo découpée dans du bois A4", prix: "15000 FCFA" }
  ],

  social: [
    { nom: "Création de contenus Tik tok", prix: "20000 FCFA" },
    { nom: "Création de publications", prix: "5000 FCFA" },
    { nom: "Traitements, restaurations et impressions de photos de tous formats", prix: "3000 FCFA" },
    { nom: "Création de catologue en ligne", prix: "50000 FCFA" },
    { nom: "Photographie professionnelle d'évènements", prix: "50000 FCFA" }
  ]
};
